---
title: "R Notebook"
output: html_notebook
---

```{r}
hours <- c( 0.50, 0.75,1.00,1.25, 1.50, 1.75,1.75,
            2.00, 2.25,2.50,2.75,3.00,3.25,3.50,4.00,
            4.25,4.50,4.75,5.00,5.50)

pass.status <- c(0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1)
```




```{r}
# data preprocessing 
# all features are in the same format.
# feature scaling and mean normalization
hours <- scale(hours)
```



```{r}
## logit probabilities
prob <- length(pass.status[pass.status==1])/length(pass.status)
logit_prob <- log(prob/(1-prob))
```





```{r}
# computing the parameters using linear algebra
ones <- rep(1, length(pass.status))
A <- matrix(c(ones, hours), nrow = length(hours))
b <- rep(logit_prob, length(pass.status))

library(matlib)
x <- inv(t(A)%*%A)%*%(t(A)%*%b)
```





```{r}
library(caret)
glm <- glm(pass.status~hours)
glm
```



```{r}
df <- read.csv('../../../Data/honors.csv')

head(df)
glm(df$hon~df$female, family = binomial)
```

```{r}
total_male <- length(df$female[df$female==0]) 
total_female <- length(df$female[df$female==1])
male_honors <- length(df$female[df$hon==1 & df$female==0])

female_honors <- length(df$female[df$hon==1 & df$female==1])

logit_male <- log(male_honors/(total_male - male_honors))
logit_female <- log(female_honors/(total_female - female_honors))
```

```{r}
n.records <- nrow(df)
ones <- rep(1, n.records)
x <- df$female
A <- matrix(c(ones,x), nrow = n.records)





b <- vector(mode="numeric", length = n.records)
for(i in 1:n.records){
  if(df$female[i]==0){
    b[i] <- logit_male
  }else{
    b[i] <- logit_female  
  }

}

x <- inv(t(A)%*%A)%*%(t(A)%*%b)
x
```

```{r}
logit_prob <- log((32/77)/(17/74))
b <- rep(logit_prob, n.records)
x <- inv(t(A)%*%A)%*%(t(A)%*%b)
x
```






```{r}
hours <- c( 0.50, 0.75,1.00,1.25, 1.50, 1.75,1.75,
            2.00, 2.25,2.50,2.75,3.00,3.25,3.50,4.00,
            4.25,4.50,4.75,5.00,5.50)

pass.status <- c(0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1)
```




```{r}
summary(lm(pass.status~hours))
```

```{r}
alpha <- -0.15394
beta <- 0.23460
b <- alpha + beta*hours
b # this is logit value
```

```{r}
ones <- rep(1, length(pass.status))
A <- matrix(c(ones, hours), nrow = length(hours))


library(matlib)
x <- inv(t(A)%*%A)%*%(t(A)%*%b)
x
```




```{r}
# standard logistic regression
glm(pass.status~hours, family=binomial)
```

